apiVersion: apps/v1
kind: Deployment
metadata:
  name: akka-cluster-scheduler-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: akka-cluster-scheduler
  strategy: {}
  template:
    metadata:
      labels:
        app: akka-cluster-scheduler
        tag: akka-cluster-scheduler-api
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      serviceAccountName: endpoints-sa
      containers:
        - env:
            - name: JAVA_OPTS
              value: "-Dconfig.resource=api-application-k8s.conf"
          image: gcr.io/gsa-sandbox-249915/akka-scheduler/akka-cluster-scheduler-app:latest
          #health
          readinessProbe:
            httpGet:
              path: /ready
              port: akka-mgmt-http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /alive
              port: akka-mgmt-http
            initialDelaySeconds: 90
            periodSeconds: 30
          #health
          name: akka-cluster-scheduler-api
          ports:
            - containerPort: 8082
            # akka remoting
            - name: remoting
              containerPort: 2552
              protocol: TCP
            # external http
            - name: akka-mgmt-http
              containerPort: 8558
              protocol: TCP
            - name: node-metrics
              containerPort: 9001
          resources: {}
      restartPolicy: Always
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: endpoint-akka-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: akka-cluster-member
subjects:
  - kind: ServiceAccount
    name: endpoints-sa
---
apiVersion: v1
kind: Service
metadata:
  name: akka-cluster-scheduler-api
  annotations:
    external-dns.alpha.kubernetes.io/hostname: scheduler.demo.lightbend.solutions.
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30082
    - name: akka-mgmt-http
      protocol: TCP
      port: 8558
      targetPort: akka-mgmt-http
      nodePort: 30559
  selector:
    tag: akka-cluster-scheduler-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: endpoints-sa