apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: cassandra-db
  name: cassandra-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cassandra-db
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: cassandra-db
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - sleep 1 && echo ' -- Pausing to let system catch up ... -->' && /docker-entrypoint.sh
              cassandra -f
          image: cassandra:3.11.11
          name: cassandra-db
          ports:
            - containerPort: 7000
            - containerPort: 7001
            - containerPort: 7199
            - containerPort: 9042
            - containerPort: 9160
          resources: {}
      hostname: cassandra-1
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  labels:
    io.kompose.service: cassandra-db
  name: cassandra-db
spec:
  ports:
    - name: "7000"
      port: 7000
      targetPort: 7000
    - name: "7001"
      port: 7001
      targetPort: 7001
    - name: "7199"
      port: 7199
      targetPort: 7199
    - name: "9042"
      port: 9042
      targetPort: 9042
    - name: "9160"
      port: 9160
      targetPort: 9160
  selector:
    io.kompose.service: cassandra-db